#!/bin/bash
set -e

uid=${UID?}
gid=${GID?}
user=${USER:-"build"}
export HOME="/home/${user}"
export PATH="/home/${user}/.local/bin:$PATH"

groupdel docker
groupadd -g "$(stat --format='%g' /var/run/docker.sock)" docker
groupadd -g "$gid" "${user}"
useradd \
	-G docker \
	-g "$gid" \
	-u "$uid" \
	-Md "/home/${user}" \
	-s /bin/bash \
	"${user}"

mkdir -p "$HOME"
chown -R "$uid:$gid" "$HOME"
cd "$HOME"
setpriv \
	--reuid="$uid" \
	--regid="$gid" \
	--init-groups \
	"$@"
