apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb-db-write
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: userdb-db-write
  template:
    metadata:
      labels:
        deployment: userdb-db-write
    spec:
      containers:
      - name: postgres
        image: registry.localhost:5000/postgres
        ports:
        - name: tcp
          containerPort: 5432
        volumeMounts:
        - mountPath: /data
          name: userdb-data
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: userdb-data
              key: password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb-api
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: userdb-api
  template:
    metadata:
      labels:
        deployment: userdb-api
    spec:
      containers:
      - name: postgrest
        image: registry.localhost:5000/postgrest
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: PGRST_SERVER_PORT
          value: 3000
        - name: PGPORT
          value: 5432
        - name: PGHOST
          value: userdb-db-write
        - name: PGDATABASE
          value: userdb
        - name: PGDATABASE
          value: userdb
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: userdb-db-write
              key: password
        - name: PGRST_DB_URL
          value: postgresql://$(PGDATABASE)?host=$(PGHOST)&user=$(PGUSER)
