apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdb-data
  labels:
    app: userdb
spec:
  storageClassName: ""
  volumeName: userdb-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: userdb-data
  labels:
    app: userdb
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /volumes/userdb/data
