apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: gitea
  template:
    metadata:
      labels:
        deployment: gitea
    spec:
      containers:
      - name: gitea
        image: registry.localhost:5000/gitea
        ports:
        - containerPort: 3000
